development:
  adapter: redis

test:
  adapter: redis

production:
  adapter: redis
  url: redis://redistogo:41c5690e6a83e3bfa2a64a02228f301d@pearlfish.redistogo.com:9693/
  channel_prefix: server_production
